services:
  mysql:
    image: mysql:8.0
    container_name: mysql_token
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: token
    volumes:
      - ./db/data:/var/lib/mysql
    platform: linux/arm64
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_0900_ai_ci']
